#!/bin/bash

set -euo pipefail

# Some tests are testing the files built by Vite are as they expect (to test
# asset preparation), so we need to make sure there's a build available first.
npm run build

# Note: We need to specify --dir so tests in the demo-app are ignored.
if [[ "$*" == *"--coverage"* ]]; then
  npx vitest --dir tests --run --coverage
else
  npx vitest --dir tests --run
fi
