#!/bin/bash

set -euo pipefail

# Some tests are testing the files built by Vite are as they expect (to test
# asset preparation), so we need to make sure there's a build available first.
npm run build

if [[ "$*" == *"--coverage"* ]]; then
  npx vitest --run --coverage --config tests/vitest.config.ts
else
  npx vitest --run --config tests/vitest.config.ts
fi
